
import type { Chapter } from './types';

export const chapters: Chapter[] = [
  {
    id: 1,
    title: "Chemical Foundations",
    questions: [
      {
        id: '1-1',
        type: 'MCQ',
        statement: 'Which of the following is an example of a quantitative observation?',
        choices: [
          'The piece of metal is longer than the piece of wood.',
          'Solution 1 is much darker than solution 2.',
          'The liquid in beaker A is blue.',
          'The temperature of the liquid is 60°C.',
          'At least two of the above (A-D) are quantitative observations.',
        ],
        correctAnswer: 'The temperature of the liquid is 60°C.',
        explanation: 'A quantitative observation involves a measurement and a unit.',
        difficulty: 'Easy',
        reference: '1.2',
        keyConcepts: [
          'Chemistry',
          'general chemistry',
          'general concepts',
          'scientific method',
        ],
        msc: 'Conceptual',
      },
      {
        id: '1-2',
        type: 'MCQ',
        statement: 'A quantitative observation',
        choices: [
          'contains a number and a unit',
          'does not contain a number',
          'always makes a comparison',
          'must be obtained through experimentation',
          'is none of these',
        ],
        correctAnswer: 'contains a number and a unit',
        explanation: 'Quantitative observations are measurements, which consist of a number and a unit.',
        difficulty: 'Easy',
        reference: '1.2',
        keyConcepts: [
          'Chemistry',
          'general chemistry',
          'general concepts',
          'scientific method',
        ],
        msc: 'Conceptual',
      },
      {
        id: '1-3',
        type: 'MCQ',
        statement: 'Generally, observed behavior that can be formulated into a statement, sometimes mathematical in nature, is called a(n)',
        choices: [
          'observation',
          'measurement',
          'theory',
          'natural law',
          'experiment',
        ],
        correctAnswer: 'natural law',
        explanation: 'A natural law is a summary of observed (measurable) behavior.',
        difficulty: 'Easy',
        reference: '1.2',
        keyConcepts: [
          'Chemistry',
          'general chemistry',
          'general concepts',
          'scientific method',
        ],
        msc: 'Conceptual',
      },
      {
        id: '1-4',
        type: 'MCQ',
        statement: "The statement 'The total mass of materials is not affected by a chemical change in those materials' is called a(n)",
        choices: [
          'observation',
          'measurement',
          'theory',
          'natural law',
          'experiment',
        ],
        correctAnswer: 'natural law',
        explanation: 'This statement, the law of conservation of mass, summarizes observed behavior.',
        difficulty: 'Easy',
        reference: '1.2',
        keyConcepts: [
          'Chemistry',
          'general chemistry',
          'general concepts',
          'scientific method',
        ],
        msc: 'Conceptual',
      },
      {
        id: '1-5',
        type: 'T/F',
        statement: 'A chemical theory that has been known for a long time becomes a law.',
        choices: ['True', 'False'],
        correctAnswer: 'False',
        explanation: 'A theory does not become a law over time; laws describe what happens, while theories explain why it happens.',
        difficulty: 'Easy',
        reference: '1.2',
        keyConcepts: [
          'Chemistry',
          'general chemistry',
          'general concepts',
          'scientific method',
        ],
        msc: 'Conceptual',
      },
      {
        id: '1-6',
        type: 'MCQ',
        statement: 'Which of the following metric relationships is incorrect?',
        choices: [
          '1 microliter = $10^{-6}$ liters',
          '1 gram = $10^3$ kilograms',
          '$10^3$ milliliters = 1 liter',
          '1 gram = $10^2$ centigrams',
          '10 decimeters = 1 meter',
        ],
        correctAnswer: '1 gram = $10^3$ kilograms',
        explanation: '1 gram = $10^{-3}$ kilograms, not $10^3$.',
        difficulty: 'Easy',
        reference: '1.3',
        keyConcepts: [
          'Chemistry',
          'general chemistry',
          'general concepts',
          'measurement',
          'SI unit',
          'prefixes',
        ],
        msc: 'Quantitative',
      },
      {
        id: '1-7',
        type: 'MCQ',
        statement: 'For which pair is the SI prefix not matched correctly with its meaning?',
        choices: [
          'mega = $10^6$',
          'kilo = 1000',
          'deci = 10',
          'nano = $10^{-9}$',
          'centi = 0.01',
        ],
        correctAnswer: 'deci = 10',
        explanation: "Deci means $10^{-1}$, not 10.",
        difficulty: 'Easy',
        reference: '1.3',
        keyConcepts: [
          'Chemistry',
          'general chemistry',
          'general concepts',
          'measurement',
          'SI unit',
          'prefixes',
        ],
        msc: 'Conceptual',
      },
      {
        id: '1-8',
        type: 'MCQ',
        statement: 'A metric unit for length is',
        choices: ['gram', 'milliliter', 'yard', 'kilometer', 'pound'],
        correctAnswer: 'kilometer',
        explanation: 'Kilometer is a metric unit of length; others are units of mass or volume.',
        difficulty: 'Easy',
        reference: '1.3',
        keyConcepts: [
          'Chemistry',
          'general chemistry',
          'general concepts',
          'measurement',
          'SI unit',
          'base unit',
        ],
        msc: 'Conceptual',
      },
      {
        id: '1-9',
        type: 'MCQ',
        statement: 'Which of the following is not a unit in the SI system?',
        choices: ['ampere', 'candela', 'Kelvin', 'meter', 'pound'],
        correctAnswer: 'pound',
        explanation: 'Pound is a unit in the imperial system, not SI.',
        difficulty: 'Easy',
        reference: '1.3',
        keyConcepts: [
          'Chemistry',
          'general chemistry',
          'general concepts',
          'measurement',
          'SI unit',
          'base unit',
        ],
        msc: 'Conceptual',
      },
      {
        id: '1-10',
        type: 'MCQ',
        statement: 'Order the four metric prefixes from smallest to largest.',
        choices: [
          'nano- < milli- < centi- < kilo-',
          'milli- < nano- < centi- < kilo-',
          'kilo- < centi- < nano- < milli-',
          'kilo- < centi- < milli- < nano-',
          'centi- < nano- < kilo- < milli-',
        ],
        correctAnswer: 'nano- < milli- < centi- < kilo-',
        explanation: 'Nano ($10^{-9}$) < milli ($10^{-3}$) < centi ($10^{-2}$) < kilo ($10^3$).',
        difficulty: 'Easy',
        reference: '1.3',
        keyConcepts: [
          'Chemistry',
          'general chemistry',
          'general concepts',
          'measurement',
          'SI unit',
          'prefixes',
        ],
        msc: 'Conceptual',
      },
      {
        id: '1-11',
        type: 'MCQ',
        statement: '8.1 kilogram(s) contains this many grams.',
        choices: [
          '$8.1 \\times 10^6$',
          '$8.1 \\times 10^3$',
          '81',
          '0.81',
          '$8.1 \\times 10^{-3}$',
        ],
        correctAnswer: '$8.1 \\times 10^3$',
        explanation: '1 kg = 1000 g → 8.1 kg = $8.1 \\times 10^3$ g',
        difficulty: 'Easy',
        reference: '1.3',
        keyConcepts: [
          'Chemistry',
          'general chemistry',
          'general concepts',
          'measurement',
          'SI unit',
          'mass',
        ],
        msc: 'Quantitative',
      },
      {
        id: '1-12',
        type: 'MCQ',
        statement: 'Convert 0.3980 m to mm.',
        choices: [
          '398.0 mm',
          '$3.980 \\times 10^{-3}$ mm',
          '$3.980 \\times 10^{-4}$ mm',
          '0.03980 mm',
          'none of these',
        ],
        correctAnswer: '398.0 mm',
        explanation: '1 m = 1000 mm → $0.3980 \\times 1000 = 398.0$ mm',
        difficulty: 'Easy',
        reference: '1.3',
        keyConcepts: [
          'Chemistry',
          'general chemistry',
          'general concepts',
          'measurement',
          'SI unit',
          'prefixes',
        ],
        msc: 'Quantitative',
      },
      {
        id: '1-13',
        type: 'MCQ',
        statement: '6.1 seconds contain this many picoseconds.',
        choices: [
          '$6.1 \\times 10^{12}$',
          '$6.1 \\times 10^{-12}$',
          '$6.1 \\times 10^{-9}$',
          '$6.1 \\times 10^9$',
          '$6.1 \\times 10^{15}$',
        ],
        correctAnswer: '$6.1 \\times 10^{12}$',
        explanation: '1 second = $10^{12}$ picoseconds → $6.1 \\times 10^{12}$ ps',
        difficulty: 'Easy',
        reference: '1.3',
        keyConcepts: [
          'Chemistry',
          'general chemistry',
          'general concepts',
          'measurement',
          'SI unit',
          'time conversion',
        ],
        msc: 'Quantitative',
      },
      {
        id: '1-14',
        type: 'MCQ',
        statement: '9.49 seconds contain this many nanoseconds.',
        choices: [
          '$9.49 \\times 10^7$',
          '$9.49 \\times 10^9$',
          '$9.49 \\times 10^{12}$',
          '$9.49 \\times 10^{10}$',
          '$9.49 \\times 10^8$',
        ],
        correctAnswer: '$9.49 \\times 10^9$',
        explanation: '1 second = $10^9$ nanoseconds → $9.49 \\times 10^9$ ns',
        difficulty: 'Easy',
        reference: '1.3',
        keyConcepts: [
          'Chemistry',
          'general chemistry',
          'general concepts',
          'measurement',
          'SI unit',
          'time conversion',
        ],
        msc: 'Quantitative',
      },
      {
        id: '1-15',
        type: 'MCQ',
        statement: 'The distance of 21 km equals',
        choices: [
          '0.021 m',
          '0.21 m',
          '210 m',
          '2100 m',
          '$2.1 \\times 10^4$ m',
        ],
        correctAnswer: '$2.1 \\times 10^4$ m',
        explanation: '1 km = 1000 m → $21 \\times 1000 = 21,000 = 2.1 \\times 10^4$ m',
        difficulty: 'Easy',
        reference: '1.3',
        keyConcepts: [
          'Chemistry',
          'general chemistry',
          'general concepts',
          'measurement',
          'SI unit',
          'prefixes',
        ],
        msc: 'Quantitative',
      },
      {
        id: '1-16',
        type: 'MCQ',
        statement: 'What is the measure of resistance an object has to a change in its state of motion?',
        choices: ['mass', 'weight', 'volume', 'length', 'none of these'],
        correctAnswer: 'mass',
        explanation: 'Mass is the measure of inertia, or resistance to change in motion.',
        difficulty: 'Easy',
        reference: '1.3',
        keyConcepts: [
          'Chemistry',
          'general chemistry',
          'general concepts',
          'measurement',
        ],
        msc: 'Conceptual',
      },
      {
        id: '1-17',
        type: 'MCQ',
        statement: 'The degree of agreement among several measurements of the same quantity is called ___ . It reflects the reproducibility of a given type of measurement.',
        choices: [
          'accuracy',
          'error',
          'precision',
          'significance',
          'certainty',
        ],
        correctAnswer: 'precision',
        explanation: 'Precision refers to reproducibility; accuracy refers to closeness to true value.',
        difficulty: 'Easy',
        reference: '1.4',
        keyConcepts: [
          'Chemistry',
          'general chemistry',
          'general concepts',
          'measurement',
        ],
        msc: 'Conceptual',
      },
      {
        id: '1-18',
        type: 'MCQ',
        statement: "As part of the calibration of a new laboratory balance, a 1.000-g mass is weighed with the following results:",
        table: "\\begin{array}{|c|c|}\n\\hline\n\\text{Trial} & \\text{Mass} \\\\\n\\hline\n1 & 1.201 \\pm 0.001 \\\\\n\\hline\n2 & 1.202 \\pm 0.001 \\\\\n\\hline\n3 & 1.200 \\pm 0.001 \\\\\n\\hline\n\\end{array}",
        choices: [
          "Both accurate and precise.",
          "Accurate but imprecise.",
          "Precise but inaccurate.",
          "Both inaccurate and imprecise.",
          "Accuracy and precision are impossible to determine with the available information."
        ],
        correctAnswer: "Precise but inaccurate.",
        explanation: "The measurements are close to each other (high precision), but they are not close to the true value of 1.000 g (low accuracy). Therefore, the balance is precise but inaccurate.",
        difficulty: "Easy",
        reference: "1.4",
        keyConcepts: [
            "Chemistry",
            "general chemistry",
            "general concepts",
            "measurement",
            "accuracy and precision"
        ],
        msc: "Conceptual",
      },
      {
        id: '1-19',
        type: 'MCQ',
        statement: 'Which of the following figure(s) represent a result having high precision?',
        choices: [
          'Figure I only',
          'Figure II only',
          'Figure III only',
          'Figure I and Figure II',
          'Figure II and Figure III',
        ],
        correctAnswer: 'Figure II and Figure III',
        explanation: 'High precision means close grouping of shots. Figures II and III show tight clusters.',
        difficulty: 'Easy',
        reference: '1.4',
        keyConcepts: [
          'Chemistry',
          'general chemistry',
          'general concepts',
          'measurement',
        ],
        msc: 'Conceptual',
      },
      {
        id: '1-20',
        type: 'MCQ',
        statement: 'Which of the following statements concerning these figures is correct?',
        choices: [
          'Figure I represents systematic error and Figure II represents random error.',
          'Figure I represents random error and Figure II represents systematic error.',
          'Figure I and Figure II represent random error.',
          'Figure I and Figure II represent systematic error.',
          'Figure III represents no errors.',
        ],
        correctAnswer: 'Figure I represents random error and Figure II represents systematic error.',
        explanation: 'Systematic error: consistent offset (Figure II). Random error: scattered but centered (Figure I).',
        difficulty: 'Easy',
        reference: '1.4',
        keyConcepts: [
          'Chemistry',
          'general chemistry',
          'general concepts',
          'measurement',
        ],
        msc: 'Conceptual',
      },
      {
        id: '1-21',
        type: 'MCQ',
        statement: 'Which of the following is the least probable concerning five measurements taken in the lab?',
        choices: [
          'The measurements are accurate and precise.',
          'The measurements are accurate but not precise.',
          'The measurements are precise but not accurate.',
          'The measurements are neither accurate nor precise.',
          'All of these are equally probable.',
        ],
        correctAnswer: 'The measurements are accurate but not precise.',
        explanation: "It's unlikely to be accurate without precision because precision affects reliability of accuracy.",
        difficulty: 'Easy',
        reference: '1.4',
        keyConcepts: [
          'Chemistry',
          'general chemistry',
          'general concepts',
          'measurement',
        ],
        msc: 'Conceptual',
      },
      {
        id: '1-22',
        type: 'MCQ',
        statement: 'Consider the following data:',
        table: "\\begin{array}{|c|c|}\\hline\n\\text{Substance} & \\text{Density (g/mL)} \\\\\n\\hline\n\\text{A} & 1.2 \\\\\n\\hline\n\\text{B} & 0.8 \\\\\n\\hline\n\\text{C} & 2.5 \\\\\n\\hline\n\\end{array}",
        choices: [
          "Substance A is the most dense.",
          "Substance B is the most dense.",
          "Substance C is the most dense.",
          "All have the same density."
        ],
        correctAnswer: "Substance C is the most dense.",
        explanation: "The table shows that substance C has the highest density value of 2.5 g/mL.",
        difficulty: "Easy",
        reference: "1.6",
        keyConcepts: [
            "Chemistry",
            "general chemistry",
            "general concepts",
            "measurement",
            "density"
        ],
        msc: "Conceptual",
      }
    ],
  },
  {
    id: 2,
    title: "Statistical Concepts in Assessment",
    questions: [
      {
        id: "2-1",
        type: "MCQ",
        statement: "What does a p-value of less than 0.05 typically indicate in statistical testing?",
        choices: ["The result is not statistically significant.", "The null hypothesis is true.", "The result is statistically significant.", "There is a 95% chance the result is correct.", "The test is invalid."],
        correctAnswer: "The result is statistically significant.",
        explanation: "In statistical hypothesis testing, the p-value is the probability of obtaining test results at least as extreme as the results actually observed, under the assumption that the null hypothesis is correct. A p-value less than 0.05 is a common threshold to reject the null hypothesis and conclude that the result is statistically significant.",
        difficulty: "Medium",
        reference: "Statistics for Dummies, Chapter 8",
        keyConcepts: ["p-value", "Statistical Significance", "Hypothesis Testing"],
        msc: "Research Methods"
      },
      {
        id: "2-2",
        type: "T/F",
        statement: "Correlation implies causation.",
        choices: ["True", "False"],
        correctAnswer: "False",
        explanation: "This is a fundamental principle in statistics. While two variables may be correlated, meaning they move in relation to each other, it does not mean that one variable causes the other to occur. There could be a third, confounding variable at play.",
        difficulty: "Easy",
        reference: "Introductory Statistics, Chapter 2",
        keyConcepts: ["Correlation", "Causation"],
        msc: "Statistical Principles"
      },
    ],
  },
  // Generate remaining chapters without questions for navigation purposes
  ...Array.from({ length: 20 }, (_, i) => ({
    id: i + 3,
    title: `Chapter ${i + 3}: Advanced Topics`,
    questions: [],
  }))
];

    